### ISSUE TITLE
Find at least one example of github repo in the following categories(anger, disgust, fear, happiness, sadness and surprise)

### ISSUE THREAD

**Issue by michiboo** [michiboo/emo2repo#4]

**Comment by nicoledanuwidjaja** [comment]
It's a tad difficult to find examples, but I looked through GitHub trending:
https://github.com/trending/developers

also found these examples:
https://github.com/fzaninotto/Faker
https://github.com/datadesk/lapd-crime-classification-analysis
https://github.com/coderchintan/Emotion-Recognition-master

**Comment by michiboo** [comment]
fixed via #19
